[package]
name = "parallax-api"
version = "0.1.0"
authors = ["Ludvig Ellevold <21200123+ljellevo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
rocket_codegen = "0.4.5"
